# Update user
PATCH  http://localhost:3333/api/user/update/644e0c70d5039cbdf17965ad HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDRlMGM3MGQ1MDM5Y2JkZjE3OTY1YWQiLCJlbWFpbCI6InVzZXJAbm90Zm91bmQubG9jYWwiLCJyb2xlIjoi0YF1c3RvbWVyIiwibGFzdG5hbWUiOiJTbWl0aCIsImZpcnN0bmFtZSI6Iktla3MiLCJpYXQiOjE2ODI4MzkwNjQsImV4cCI6MTY4Mjg0NTA2NH0.Xutvpg99FauD93n4d6_4YB5l8MlGzxi8Wr8pyHMO0ak

{
  "dateBirth": "2012-02-22",
  "firstname": "KeksX",
  "lastname": "SmithX",
  "city": "Москва",
  "specialization": "Курьер",
  "info": "info"
}

###

# Get user by ID customer
GET http://localhost:3333/api/user/customer/644e0c70d5039cbdf17965ad HTTP/1.1

###

# Get user by ID executer
GET http://localhost:3333/api/user/executer/644e0c70d5039cbdf17965ad HTTP/1.1

###
